/**
 * Anchor IDL types for the on-chain Konfide program.
 *
 * Stub: the real IDL will be generated by `anchor build` from
 * `packages/contracts/programs/konfide` and emitted to `target/idl/`.
 * Until then, this declares an empty placeholder type that downstream code
 * can import without breaking.
 */

export interface KonfideIdl {
  readonly version: string
  readonly name: 'konfide'
}

export const KONFIDE_PROGRAM_ID = '11111111111111111111111111111111'
